import java.io.*;
class addons
{void main()throws Exception
    {System.out.println("                                  |\\   |\\");
     System.out.println("                                  | \\  | \\");
     System.out.println("                                  | /  | /");
     System.out.println("                                  |/   |/      Premier      "         );
     System.out.println("                                  |    |\\     Badminton          ");
     System.out.println("                                  |    | \\");
     System.out.println("                                  |    | /");
     System.out.println("                                  |    |/");
     Thread.sleep(1000);
     System.out.println("\u000c");
     System.out.println("                                                     __________                          ");
     Thread.sleep(1000);
     System.out.println("                                                    /          \\     ");
     Thread.sleep(1000);
     System.out.println("                                                   |            |     __  __  __        ");              
     Thread.sleep(1000);
     System.out.println("                                                   |   LEAGUE   |     \\ \\/  \\/  \\ ");       
     Thread.sleep(1000);
     System.out.println("                                                   |     OF     |      \\        /");
     Thread.sleep(1000);
     System.out.println("                                                   |  CHAMPIONS |       \\      /");
     Thread.sleep(1000);
     System.out.println("                                                   |            |        \\    /");
     Thread.sleep(1000);
     System.out.println("                                                   |            |        \\----/ ");
     Thread.sleep(1000);
     System.out.println("                                                   |            |         \\__/");
     Thread.sleep(1000);
     System.out.println("                                                   |            |   ");
     Thread.sleep(1000);
     System.out.println("                                                   |            |");
     Thread.sleep(1000);
     System.out.println("                                                    \\          /");
     Thread.sleep(1000);
     System.out.println("                                                     \\        /");
     Thread.sleep(1000);
     System.out.println("                                                      \\__||__/     ");
     Thread.sleep(1000);
     System.out.println("                                                         ||");
     Thread.sleep(1000);
     System.out.println("                                                         ||");
     Thread.sleep(1000);
     System.out.println("                                                         ||");
     Thread.sleep(1000);
     System.out.println("                                                         ||");
     Thread.sleep(1000);
     System.out.println("                                                         ||");
     Thread.sleep(1000);
     System.out.println("                                                         ||");
     Thread.sleep(1000);
     System.out.println("                                                         ||");
     Thread.sleep(1000);
     System.out.println("                                                         ||");
     Thread.sleep(1000);
     System.out.println("                                                         ||");
     Thread.sleep(1000);
     System.out.println("                                                         ||");
     Thread.sleep(1000);
     System.out.println("                                                         ||");
     Thread.sleep(1000);
     System.out.println("                                                         ||");
     Thread.sleep(1000);
     System.out.println("                                                         ||");
     Thread.sleep(1000);
     System.out.println("                                                        /  \\");
     Thread.sleep(1000);
     System.out.println("                                                       /____\\");
     Thread.sleep(1000);
     System.out.println("                                                       |    |");
     Thread.sleep(1000);
     System.out.println("                                                       |    |");
     Thread.sleep(1000);
     System.out.println("                                                       |    |");
     Thread.sleep(1000);
     System.out.println("                                                       |    |");
     Thread.sleep(1000);
     System.out.println("                                                       |    |");
     Thread.sleep(1000);
     System.out.println("                                                       |    |");
     Thread.sleep(1000);
     System.out.println("                                                       |    |");
     Thread.sleep(1000);
     System.out.println("                                                       |    |");
     Thread.sleep(1000);
     System.out.println("                                                       |____|");}}      
                                                       

          